Feature/dev to
Goran94mkd/SEMOS-domasni pull request #8
Opened 2020-11-10 13:13 UTC by Goran94mkd

2020-11-10 22:27 UTC, dpeshevski requested changes
Поправи ги коментарите.

2020-11-10 22:27 UTC, dpeshevski commented on dev-to/example1.css
> +}
h1,
h2, 
h3 {
//style here
}

2020-11-10 22:27 UTC, dpeshevski commented on dev-to/example3.css
> +html, body { background: #557; }
во нов ред.

2020-11-10 22:27 UTC, dpeshevski commented on dev-to/example3.css
> +background: #ccc;
Ти фали празен простор. :)

2020-11-12 01:29 UTC, Goran94mkd commented on dev-to/example1.css
> +}
Корегирано.

2020-11-12 01:29 UTC, Goran94mkd commented on dev-to/example3.css
> +html, body { background: #557; }
Корегирано.

2020-11-12 01:29 UTC, Goran94mkd commented on dev-to/example3.css
> +background: #ccc;
Корегирано.

2020-11-13 10:31 UTC, dpeshevski requested changes

2020-11-13 10:31 UTC, dpeshevski commented on dev-to/example3.css
> +}
```
html,
body {
   background: #557;
}
```

2020-11-13 10:31 UTC, dpeshevski commented on dev-to/example2.css
> +}
```
h1,
h2,
h3 {
  margin: 0;
  font-weight: 700;
}
```

2020-11-13 10:31 UTC, dpeshevski commented on dev-to/example2.html
> +</html>
ти се жали ова :)

2020-11-13 22:36 UTC, Goran94mkd commented on dev-to/example2.css
> +}
Корегирано.

2020-11-13 22:36 UTC, Goran94mkd commented on dev-to/example2.html
> +</html>
Корегирно.

2020-11-13 22:38 UTC, Goran94mkd commented on dev-to/example3.css
> +}
Корегирано :) 
Види кога ќе си слободен, уште за домашна број 3 направив PR, и да се насочуваме полека кон JS :D 
Поздрав.

2020-11-24 07:53 UTC, dpeshevski approved these changes

2020-11-24 11:30 UTC, merged